### ISSUE TITLE
Font size is not propagated correctly to find window on Linux

### ISSUE THREAD

**Issue by vanniktech** [randy3k/SyntaxMgr#13]
I've got the following settings:

```
{
    "syntaxmgr_settings":[
        {
            "platforms": ["linux"],
            "settings": {
                "font_size": 8
            }
        },
        {
            "platforms": ["osx"],
            "settings": {
                "font_size": 12
            }
        }
    ]
}
```

When I'm opening Sublime on my Linux it displays the font size correctly as 8px. When I want to search for something though it uses the default font size, which is 12 or 13.

**Comment by randy3k** [comment]
It is expected as Syntax Manager only applies the settings to the syntax, not the layout. To change the font size of the layout, you need to edit the global preferences.

**Comment by vanniktech** [comment]
Hmm that's a bummer then. I guess we can close this issue then as it's out of the scope for this plugin?
