### ISSUE TITLE
warning: mnemonic P not found in menu caption Syntax Manager

### ISSUE THREAD

**Issue by AndreTheHunter** [randy3k/SyntaxMgr#9]
I get the following warning in the Sublime Text 3 console:
```
warning: mnemonic P not found in menu caption Syntax Manager
```
I'm not sure what it means but I thought I'd let you know.

**Comment by randy3k** [comment]
should be fixed now.

**Comment by unsabi** [comment]
Hi, I now have this warning:
`warning: mnemonic s not found in menu caption Syntax Manager`

I think you need to replace the mnemonic 's' to 'S'.

**Comment by randy3k** [comment]
@AndreTheHunter could you confirm if it has been fixed or not?

**Comment by gwenzek** [comment]
I also have the `warning: mnemonic s not found in menu caption Syntax Manager`
